"""create tables

Revision ID: b7d6ce81c36f
Revises: 
Create Date: 2023-10-30 23:14:41.269741

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b7d6ce81c36f"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "Version",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("file_name", sa.VARCHAR(length=256), nullable=False),
        sa.Column("loaded_date_unix", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "project",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("code", sa.Integer(), nullable=False),
        sa.Column("project_name", sa.VARCHAR(length=128), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_project_code"), "project", ["code"], unique=True)
    op.create_index(
        op.f("ix_project_project_name"),
        "project",
        ["project_name"],
        unique=False,
    )
    op.create_table(
        "value",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("project_code", sa.Integer(), nullable=False),
        sa.Column("date", sa.DateTime(), nullable=False),
        sa.Column("plan", sa.Integer(), nullable=False),
        sa.Column("fact", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_code"],
            ["project.code"],
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_value_id"), "value", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_value_id"), table_name="value")
    op.drop_table("value")
    op.drop_index(op.f("ix_project_project_name"), table_name="project")
    op.drop_index(op.f("ix_project_code"), table_name="project")
    op.drop_table("project")
    op.drop_table("Version")
    # ### end Alembic commands ###
